# Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
from math import sqrt
idx = 3
nth = 0
sum = 0
while nth < 4000000:
    nth = (((1+sqrt(5))**idx)-((1-sqrt(5)))**idx)/(2**idx*sqrt(5))
    idx += 3
    sum += int(nth)

print ("Problem 2: ", sum)